#SPDX-License-Identifier: MIT-0
---
# tasks file for local_ssh_config
- name: Ensure .ssh directory exists
  file:
    path: "{{ ansible_env.HOME }}/.ssh"
    state: directory
    mode: '0700'

- name: Deploy local SSH config
  template:
    src: local_ssh_config.j2
    dest: "{{ ansible_env.HOME }}/.ssh/config"
    mode: '0600'