{
 "title": "New dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Panel Title",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 * (1 - (node_filesystem_avail_bytes{instance=\"10.0.10.202:9100\", device=\"/dev/root\", fstype=\"ext4\"} / node_filesystem_size_bytes{instance=\"10.0.10.202:9100\", device=\"/dev/root\", fstype=\"ext4\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DISK SPACE USED % llm2",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 * (1 - (node_filesystem_avail_bytes{instance=\"10.0.11.89:9100\", device=\"/dev/root\", mountpoint=\"/etc/hosts\"} / node_filesystem_size_bytes{instance=\"10.0.11.89:9100\", device=\"/dev/root\", mountpoint=\"/etc/hosts\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CHAT/10mins llm1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (host) (\r\n  count_over_time({host=\"llm1\", service_name=\"ollama\"} |= \"/api/chat\" [10m])\r\n)"
    }
   ]
  },
  {
   "title": "CHAT/10mins llm2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by (host) (\r\n  count_over_time({host=\"llm2\", service_name=\"ollama\"} |= \"/api/chat\" [10m])\r\n)"
    }
   ]
  },
  {
   "title": "MEMORY USED % 10.0.10.202",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - (node_memory_MemAvailable_bytes{instance=\"10.0.10.202:9100\"} / node_memory_MemTotal_bytes{instance=\"10.0.10.202:9100\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MEMORY USED % 10.0.11.89",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - (node_memory_MemAvailable_bytes{instance=\"10.0.11.89:9100\"} / node_memory_MemTotal_bytes{instance=\"10.0.11.89:9100\"}))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}